wandb_version: 1

Dataset:
  desc: null
  value: Texas
Hidden dimension in GRAFF:
  desc: null
  value: 64
Loss type:
  desc: null
  value: ce
N° Hidden layer:
  desc: null
  value: 2
ODE step:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: Loss on train
      5: 1
      6:
      - 1
    - 1: Accuracy on train
      5: 1
      6:
      - 1
    - 1: Loss on test
      5: 1
      6:
      - 1
    - 1: Accuracy on test
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    python_version: 3.9.15
    start_time: 1684680386.035366
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 77
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 77
      3:
      - 2
      - 7
      - 13
      - 16
      - 23
      4: 3.9.15
      5: 0.13.7
      6: 4.24.0
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 183
learning rate:
  desc: null
  value: 0.001
weight decay:
  desc: null
  value: 0
