wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1684681621.751141
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 77
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 77
      3:
      - 19
      - 23
      4: 3.9.15
      5: 0.13.7
      6: 4.24.0
      8:
      - 1
      - 5
lr:
  desc: null
  value: 0.001
