wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: Loss on train
      5: 1
      6:
      - 1
    - 1: Accuracy on train
      5: 1
      6:
      - 1
    - 1: Loss on test
      5: 1
      6:
      - 1
    - 1: Accuracy on test
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    python_version: 3.9.15
    start_time: 1684682832.271259
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 77
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 77
      3:
      - 2
      - 7
      - 23
      - 37
      4: 3.9.15
      5: 0.13.7
      6: 4.24.0
      8:
      - 1
      - 5
hidden_dim:
  desc: null
  value: 1024
loss_type:
  desc: null
  value: nll
lr:
  desc: null
  value: 0.001
num_layers:
  desc: null
  value: 3
step:
  desc: null
  value: 0.4
wd:
  desc: null
  value: 0
